### ISSUE TITLE
iOS 14.5 Support

### ISSUE THREAD

**Issue by markst** [Stampoo/SnapshotSafeView#1]
Fails to render view on iOS 14.5:

| iOS 14.5  | iOS 15.0 |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 8 - 2022-07-21 at 12 29 47](https://user-images.githubusercontent.com/274318/180203382-1189ef78-b4e0-454f-8372-7b6093555548.png)  | ![Simulator Screen Shot - iPhone 8 - 2022-07-21 at 12 30 16](https://user-images.githubusercontent.com/274318/180203394-e583f231-ebc9-4459-a1f2-4e5d9b5194a5.png) |

**Comment by markst** [comment]
My previous implementation checked for availability:
```
// iOS 14.1 -> _UITextFieldCanvasView
// iOS 15.0 -> _UITextLayoutCanvasView
if let klass = NSClassFromString("_UITextFieldCanvasView") as? UIView.Type {
    hiddenView = klass.init()
    hiddenView.layer.perform(Selector(("setDisableUpdateMask:")), with: 0x12)
} else {
    let textField = UITextField()
    textField.isSecureTextEntry = true
    hiddenView = textField.layer.sublayers?.first?.delegate as! UIView
    hiddenView.subviews.forEach { $0.removeFromSuperview() }
}
```

**Comment by markst** [comment]
iOS 14.5 is returning here: https://github.com/Stampoo/SnapshotSafeView/blob/master/Sources/SnapshotSafeView/Core/ScreenshotInvincibleContainer.swift#L63

**Comment by markst** [comment]
https://gist.github.com/damian-rzeszot/bbfd92895dfe9400ba9a7cf2a0c1e670

**Comment by Stampoo** [comment]
@markst Hi, thanks for solution, this was fixed there 🙃  https://github.com/Stampoo/SnapshotSafeView/pull/2

**Comment by markst** [comment]
Thanks @Stampoo! I'll give it a go
