### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by mendozammatias** [Stampoo/SnapshotSafeView#15]
Hi, 

I think this would be a great solution to prevent screenshots on React Native apps.

I tried to integrate it by unfortunately, my swift and Objective C knowledge is very limited.

In case I could help on the React Native side implementation, count with me!

**Comment by Stampoo** [comment]
Hey @mendozammatias, this is awesome idea :)
i planning this on next release

**Comment by Stampoo** [comment]
@mendozammatias Hello, you can try https://github.com/Stampoo/SnapshotSafeView/blob/master/Documentation/React-Native.md 🙃. Tell me, please, about result.

**Comment by WickednessPro** [comment]
@Stampoo I got it working perfectly with react native!

**Comment by mendozammatias** [comment]
It works like a charm! Really thank you 🙌🏼

**Comment by mehthabux** [comment]
@mendozammatias is these any example repo?

**Comment by mehthabux** [comment]
@Stampoo thank you too much, much appreciate
