### ISSUE TITLE
A second keyboard appears when there is a TextField inside the container

### ISSUE THREAD

**Issue by EmaCorons** [Stampoo/SnapshotSafeView#21]
Hi, I'm applying your solution to my project and I noticed that, using the TextField and interacting with it, a second keyboard appears behind the TextField keyboard. On dismissing the TextField keyboard, this second keyboard will be visible and allows you to interact with the ProtectiveContainer (in fact, when writing, a secure text appears on the screen). I tried calling resignFirstResponder() on the container at the same time I dismiss the TextField keyboard and the keyboard disappears, but the view seems to be disabled, preventing any interaction.

**Comment by Stampoo** [comment]
@EmaCorons Hello, do you use `0.1.1` or version from the `master`?

**Comment by EmaCorons** [comment]
I'm using the 0.1.1 version

**Comment by Stampoo** [comment]
@EmaCorons Please, try to https://github.com/Stampoo/SnapshotSafeView/blob/master/Documentation/Swift.md load this package from `master`

**Comment by EmaCorons** [comment]
@Stampoo I just tried and it works perfectly! Thank you very much!

**Comment by Stampoo** [comment]
@EmaCorons https://github.com/Stampoo/SnapshotSafeView/releases/tag/0.2.0 it should work too 🙃
