### ISSUE TITLE
CocoaPods installation issue

### ISSUE THREAD

**Issue by ftbwatech** [Stampoo/SnapshotSafeView#23]
Hello. 

I tried to add this to my project through CocoaPods -sadly, our project still depends on it- however it throws an error and a warning saying 

`The `SnapshotSafeView` pod failed to validate due to 1 error:
    - WARN  | description: The description is equal to the summary.
    - ERROR | [iOS] File Patterns: The SnapshotSafeView (0.2.0) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).
`

The line added to `Podfile` is 

`pod 'SnapshotSafeView', :git => 'https://github.com/Stampoo/SnapshotSafeView.git', :tag => '0.2.0'`

Then I added source code manually into project and it does the job perfectly. But I still want to separate it. 

Can you help?

**Comment by Stampoo** [comment]
Hello, sure, I'll deal with this issue today.

**Comment by ftbwatech** [comment]
Thanks. Then I will wait for you before merging the feature.

**Comment by Stampoo** [comment]
Done:)
https://github.com/Stampoo/SnapshotSafeView/releases/tag/0.2.1

**Comment by ftbwatech** [comment]
Thanks. It has been fixed when I removed `: tag => '0.2.1'` from Podfile. Seems like podspec is still broken and not updated on `0.2.1`. Just fyi :)
