### ISSUE TITLE
Cannot reproduce React Native example

### ISSUE THREAD

**Issue by jonathan-price-softwire** [Stampoo/SnapshotSafeView#30]
I've been trying to test out the React Native example of this package.

I downloaded the `React-Native-example` branch from https://github.com/Stampoo/SnapshotSafeView/tree/React-Native-example

I initially had the following error when performing `pod install`
```
[!] Failed to load 'SnapshotSafeView' podspec: 
[!] Invalid `SnapshotSafeView.podspec` file: syntax error, unexpected '<'
<!DOCTYPE html>
```
I got around this by commenting out the following line from the `Podfile`
```
pod 'SnapshotSafeView', :podspec => 'https://github.com/Stampoo/SnapshotSafeView'
```
I don't believe this line is necessary, because the package is being installed with Swift Package Manager not CocoaPods.

I then ran the app on a simulator using `npm run start` and `npm run ios`.

But when I take a screenshot I see the content inside the `<SnapshotSafeView>`

Are there any constraints that I should be aware of?
* I've tried both an iOS 14 and 16 simulator
* Does the package work when using the simulator's screenshot button?

![Simulator Screen Shot - iPhone 14 - 2023-03-01 at 20 14 23](https://user-images.githubusercontent.com/122103259/222258080-0683ca17-c7a4-48f8-804c-e29dbc680bd5.png)

**Comment by Stampoo** [comment]
@jonathan-price-softwire Hi, I'll check the example, there are mistakes there.
But on the simulator, this works only with the marked green:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/44356536/222258948-8a5b99e3-a169-430c-9851-4a1a812eaf3a.png">

And a package in the example's branch without relevant changes 🙃

**Comment by jonathan-price-softwire** [comment]
Thank you so much! 
When I use that "Trigger Screenshot" button the content is not present.
