### ISSUE TITLE
Is this lib that used in the app can pass apple review?

### ISSUE THREAD

**Issue by edison0951** [Stampoo/SnapshotSafeView#7]
I found this lib that have used `_UITextLayoutCanvasView` and `_UITextFieldCanvasView`. That class is private api. If I use this lib in our app, can we pass the apple review?

**Comment by Stampoo** [comment]
Hey:)
Currently, the application using this library will be releasing in the `AppStore`, I can say 100% after 09/28/2022.
But it was successful reviewing for external testing in `TestFlight`.

**Comment by edison0951** [comment]
Thanks for your reply. Why is there no iOS 13 support for getHiddenContainerTypeInStringRepresentation function?

**Comment by Stampoo** [comment]
In iOS 13 was used same class, that ios 12, if i not mistaken. I check this in closest weekends.

**Comment by edison0951** [comment]
Thanks for your reply. I will test for iOS 16 and iOS 13.

**Comment by Stampoo** [comment]
> I have tested UITextField in the iOS 13 Simulator, the name of the first subview is the same as iOS 14, not iOS 12.

Awesome, thanks, i will add fix in closest time! :)

**Comment by ucerxxx** [comment]
> @edison0951
> Hey:)
> Currently, the application using this library will be releasing in the `AppStore`, I can say 100% after 09/28/2022.
> But it was successful reviewing for external testing in `TestFlight`.

Any updates? have you passed the review?

**Comment by Stampoo** [comment]
@ucerxxx Hello, our release dragged on a little and we are waiting for it after 11/01/2022 😢. But i exactly notify about results 😃

**Comment by ucerxxx** [comment]
> @ucerxxx Hello, our release dragged on a little and we are waiting for it after 11/01/2022 😢. But i exactly notify about results 😃

why not passing the app to review with `manually release` option - even if it will be approved - you can remove this version from release))) but at least you will be ready for `surprises`)))

**Comment by Stampoo** [comment]
@ucerxxx  Yep, this very smart move, but i can't control this by my working reason 🙃 .
But we already passed external testing in Appstore connect(This have static analyse of code too).

**Comment by Stampoo** [comment]
@ucerxxx, @edison0951 Hello, we completely passed review in App Store without issues 😃

**Comment by edison0951** [comment]
that is great!

**Comment by edison0951** [comment]
> @ucerxxx, @edison0951 Hello, application completely passed review in App Store without issues 😃

that is great!

**Comment by Stampoo** [comment]
@edison0951 Application is release!
