### ISSUE TITLE
How to connect with SwiftUi?

### ISSUE THREAD

**Issue by pagedimka** [Stampoo/SnapshotSafeView#8]
Can you please tell me how to use it in SwiftUi?  do I need to just put the final class in the AppDelegate? I'm new, thanks

**Comment by Stampoo** [comment]
Hey @pagedimka, today, i will add lazy support `SwiftUI` and updating `README.me` with example for `SwiftUI` 🙃

**Comment by Stampoo** [comment]
> Can you please tell me how to use it in SwiftUi? do I need to just put the final class in the AppDelegate? I'm new, thanks

SwiftUI support successfully added in https://github.com/Stampoo/SnapshotSafeView/releases/tag/0.1.0, u can see example in https://github.com/Stampoo/SnapshotSafeView/blob/master/README.md

**Comment by pagedimka** [comment]
Thank you very much!
